config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :tvs do
    resources :likes, only: [:create, :destroy]
  end
  root 'tvs#index'
   resources :sindans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :tv
  validates_uniqueness_of :tv_id, scope: :user_id
end

app/models/tv.rb
class Tv < ApplicationRecord
    belongs_to :user
    mount_uploader :image, ImageUploader
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :tvs, dependent: :destroy
         has_many :likes, dependent: :destroy
         has_many :liked_tvs, through: :likes, source: :tv
         def already_liked?(tv)
          self.likes.exists?(tv_id: tv.id)
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(tv_id: params[:tv_id]) #user_idとtweet_idの二つを代入
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(tv_id: params[:tv_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
    
end

app/controllers/sindans_controller.rb
class SindansController < ApplicationController
    def index
    end
end

app/controllers/tvs_controller.rb
class TvsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
    def index
      @dorama = Tv.where(favorite: "ドラマ")
      @variety = Tv.where(favorite: "バラエティ")
      @eiga = Tv.where(favorite: "映画")
      @anime = Tv.where(favorite: "アニメ")
      @tv_like_ranks = Tv.find(Like.group(:tv_id).order('count(tv_id) desc').pluck(:tv_id))
    end
    def new
        @tvs = Tv.new
      end
    
      def create
        tv = Tv.new(tv_params)
        tv.user_id = current_user.id
        if tv.save!
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end
      def show
        @tv = Tv.find(params[:id])
      end
      def edit
        @tv = Tv.find(params[:id])
      end
      def update
        tv = Tv.find(params[:id])
        if tv.update(tv_params)
          redirect_to :action => "show", :id => tv.id
        else
          redirect_to :action => "new"
        end
        def destroy
          tv = Tv.find(params[:id])
          tv.destroy
          redirect_to action: :index
        end
      end
      private
      def tv_params
        params.require(:tv).permit(:name, :genre, :actor, :about, :title, :image, :favorite)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/sindans_helper.rb
module SindansHelper
end

app/helpers/tvs_helper.rb
module TvsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Video</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%#= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

 <main>
  <%= yield %>
 </main>
</body>
 
</html>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&display=swap" rel="stylesheet">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Kosugi+Maru&family=Noto+Serif:wght@900&family=Protest+Strike&family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">

app/views/tvs/edit.html.erb
<%= form_for @tv do |f| %>
    # データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :テーマ %>
    <%= f.text_field :name, :size => 30 %>
  </div>

# データ型がstringで選択式の入力フォーム
  <div class="field">
    <%= f.label :ジャンル  %>
    <%= f.select :genre, 
    [["ドラマ", "ドラマ"], 
    ["アニメ", "アニメ"], 
    ["バラエティー番組", "バラエティー番組"],
    ["ドキュメンタリー", "ドキュメンタリー"],
    ["音楽番組", "音楽番組"]], include_blank: "選択して下さい" %>
  </div>

  # データ型がstringで自由記述の入力フォーム
  <div class="field">
    <%= f.label :出演者 %>
    <%= f.text_field :actor, :size => 30 %>
  </div>

  # データ型がtextで自由記述の入力フォーム
  <div class="field">
    <%= f.label :番組内容  %>
    <%= f.text_area :about, :size => "30x2" %>
  </div>

   # データ型がstringで自由記述の入力フォーム
   <div class="field">
   <%= f.label :番組名 %>
   <%= f.text_field :title, :size => 30 %>
 </div>
    <%= f.submit "編集する" %>
  <% end %>

app/views/tvs/index.html.erb
<h1>CONTENTSHOW</h1>
<div class="tvs-container">

<div class="dorama"> 
<h2>ドラマ</h2>
<% @dorama.each do |t| %>
  <div class="dm">
  <br><br><%= image_tag t.image_url, size: "400x300" if t.image? %>
  
  </div>
<% end %>
</div>

<div class="variety"> 
<h2>バラエティ</h2>
<% @variety.each do |t| %>
  <div class="vr">
  <br><br><%= image_tag t.image_url, size: "400x300" if t.image? %>
  
  </div>
<% end %>
</div>

<div class="eiga"> 
<h2>映画</h2>
<% @eiga.each do |t| %>
  <div class="mv">
  <br><br><%= image_tag t.image_url, size: "400x300" if t.image? %>
  
  </div>
<% end %>
</div>

<div class="anime"> 
<h2>アニメ</h2>
<% @anime.each do |t| %>
  <div class="am">
  <br><br><%= image_tag t.image_url, size: "400x300" if t.image? %>
  
  </div>
<% end %>
</div>
</div>
<div class="kinou">
<br><br><br><%= button_to '診断機能へ', sindans_path, method: :get, class:"kc"%>
</div>

<br><br><%= link_to '新規投稿へ', new_tv_path, method: :get, class:"sinki" %>
いいねランキング
<% @tv_like_ranks.each.with_index(1) do |t, i| %>
  第<%= i %>位
:
<%= image_tag t.image_url, size: "400x300" if t.image? %>
:
<% end %>

app/views/tvs/new.html.erb
<h1 class="newpost">NEW POST</h1>
<div class="posting">
<br><br><br>
<%= form_for @tvs do |f| %>
<br><br><br>
  <div class="theme">
    <%= f.label :テーマ %>
    <%= f.text_field :name, :size => 50 %>

    <br><br><br><br>
  </div>

  <div class="genre">
    <%= f.label :ジャンル  %>
    <%= f.select :genre, 
    [["ドラマ", "ドラマ"], 
    ["バラエティ", "バラエティ"],
    ["映画", "映画"], 
    ["アニメ", "アニメ"]], include_blank: "選択して下さい" %>
    <br><br><br><br>
  </div>

  <div class="name">
  <%= f.label :番組名 %>
  <%= f.text_field :title, :size => 50 %>
  <br><br><br><br>
  </div>

  <div class="content">
    <%= f.label :番組内容  %>
    <%= f.text_area :about, :size => "60x20" %>
    <br><br><br><br>
  </div>

  <div class="actor">
    <%= f.label :出演者 %>
    <%= f.text_field :actor, :size => 50 %>
    <br><br><br><br>
  </div>

  <div class="photo">
    <%= f.label :画像投稿 %>
    <%= f.file_field :image %>
    <br><br><br><br><br><br><br><br><br>
  </div>
  
  <%= f.submit "投稿する", class:"post" %>
    <% end %>
    
</div>

<div class="look">
 <%= link_to "一覧に戻る", tvs_path %>
</div>

app/views/tvs/show.html.erb
<h1>詳細ページ</h1>
<h3>Tweet詳細</h3>
<div class="tv">
  <p><%= @tv.title %></p>
  <p><%= @tv.created_at %></p>
  <% if user_signed_in? %>
      <% if current_user.already_liked?(@tv) %>
        <%= button_to tv_like_path(@tv), method: :delete do %>
          <p>いいねを取り消す</p><%= @tv.likes.count %>
        <% end %>
      <% else %>
        <%= button_to tv_likes_path(@tv), method: :post do %>
          <p>いいね</p><%= @tv.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @tv.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_tv_path(@tv.id) %>
</div>

<h2>いいねしたユーザー</h2>
<% @tv.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<%= link_to "Tweet一覧に戻る", tvs_path %>

<%= link_to "編集する", edit_tv_path(@tv.id) %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>